apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: default
spec:
  serviceAccountName: demo-sa
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: secure-container
    image: nginxinc/nginx-unprivileged:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
